global:
  scrape_interval: 5s

scrape_configs:
  # Scrape OpenTelemetry Collector's Prometheus exporter
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
        labels:
            environment: development

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
            environment: development

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
            environment: development